language: python
python:
  - "3.7"

before_install:
  - sudo apt-get install -y xvfb libqt5x11extras5

install:
  - pip3 install --upgrade pip
  - pip install tox

script:
  - tox

#after_success:
#  - coveralls