language: python
python:
  - "3.7"

#before_install:
#  - sudo apt-get install -y xvfb libqt5x11extras5

install:
#  - pip install -e .
  - pip3 install --upgrade pip
  - pip install poetry tox

script:
  - tox
#  - python setup.py test

#after_success:
#  - coveralls