name: pharedox
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - xarray
  - scikit-image
  - scipy
  - numba
  - tqdm
  - sphinx_rtd_theme
  - jupyter
  - jupyterlab
  - black
  - sphinx
  - numpydoc
  - statsmodels
  - seaborn
  - matplotlib
  - scikit-learn
  - netcdf4
  - pandas
  - pyqt
  - keras
  - pylint
  - cached-property
  - sphinx-autodoc-typehints
  - pytest
  - pytest-xdist
  - pytest-cov
# prefix: /Users/sean/opt/anaconda3/envs/pharedox
