name: pharedox
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7

  # Numerical
  - numpy
  - xarray
  - scikit-image
  - scipy
  - numba
  - scikit-learn
  - keras
  - pandas
  - statsmodels

  # Viz
  - matplotlib
  - seaborn
  - pyqt
  - pyqtgraph
  - tqdm

  # Testing
  - pytest
  - pytest-xdist
  - pytest-cov

  # Docs
  - sphinx
  - sphinx_rtd_theme
  - sphinx-autodoc-typehints
  - numpydoc

  # Misc / Utils
  - cached-property
  - netcdf4
  - jupyter
  - jupyterlab

  # Code tools
  - pylint
  - black

# prefix: /Users/sean/opt/anaconda3/envs/pharedox
