function [reg_rgh_410, reg_rgh_470, warpfd, wfd, d410, reg_d470] = ...
    channel_register_discrete(...
    meas_410, meas_470, ...
    WARP_N_BASIS, WARP_ORDER, WARP_LAMBDA,...
    SMOOTH_LAMBDA, SMOOTH_N_BREAKS, SMOOTH_ORDER, ...
    ROUGH_LAMBDA, ROUGH_N_BREAKS, ROUGH_ORDER,...
    N_DERIV,...
    resample_resolution)

[reg_rgh_410, reg_rgh_470, warpfd, wfd, d410, reg_d470] = channel_register(...
    meas_410, meas_470, ...
    WARP_N_BASIS, WARP_ORDER, WARP_LAMBDA,...
    SMOOTH_LAMBDA, SMOOTH_N_BREAKS, SMOOTH_ORDER, ...
    ROUGH_LAMBDA, ROUGH_N_BREAKS, ROUGH_ORDER,...
    N_DERIV);

xs = linspace(0, 1, resample_resolution);
reg_rgh_410 = eval_fd(xs, reg_rgh_410);
reg_rgh_470 = eval_fd(xs, reg_rgh_470); 
warpfd = eval_fd(xs, warpfd);
wfd = eval_fd(xs, wfd);
d410 = eval_fd(xs, d410);
reg_d470 = eval_fd(xs, reg_d470);
end