function  lnorm2x2 = square(data) 
%   SQUARE formats Plot Values to cropped and square intensity matrix
%   This function takes as argument the Plot Value.txt matrix generated by
%   the multiplot function in ImageJ,where Xi= vector of pixel coordinates 
%   and Yi= vector of intensities.
%   This function process each pair of vectors XiYi at a time. First crops
%   the zero elements plus the 2 first and last elements. Second scale and
%   interpolates both vectors to a length normalized vector  (100 rows).
%   The new pair of normalized vectors (lnx and lny) are then stored in a
%   new squared matrix (save as output while denugging)

m=data; % duplicate original matrix 
ncols=size(m,2);
New= zeros(100,ncols); % New length normalized matrix to store lnx and lny pairs

%i=ncols/2;

for i=2:2:ncols
    xiyi=m(:,(i-1):(i)); %pick a pair of xiyi at a time
    
   for j=1:size(xiyi,1)     %replace NaN = 0
       if isnan(xiyi(j,2))
       xiyi(j,2)=0;
       end
    end
    
    yfirst=find(xiyi(:,2),1,'first');
    ylast=find(xiyi(:,2),1,'last');
    crop= xiyi((yfirst+3):(ylast-3),:);
    lnx_lny=resizem(crop,[100,2],'bilinear');
    New(:,(i-1):(i))=lnx_lny;   
end
lnorm2x2 = New;
