# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/sean/code/pharedox/pharedox/gui/qt_ui_files/image_stack_widget.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_XArrayDisplayWidget(object):
    def setupUi(self, XArrayDisplayWidget):
        XArrayDisplayWidget.setObjectName("XArrayDisplayWidget")
        XArrayDisplayWidget.resize(1075, 679)
        self.gridLayout_2 = QtWidgets.QGridLayout(XArrayDisplayWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(XArrayDisplayWidget)
        self.widget.setMinimumSize(QtCore.QSize(300, 0))
        self.widget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.wvlBox = QtWidgets.QComboBox(self.groupBox_2)
        self.wvlBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.wvlBox.setObjectName("wvlBox")
        self.verticalLayout_3.addWidget(self.wvlBox)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.pairSlider = QtWidgets.QSlider(self.groupBox_2)
        self.pairSlider.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pairSlider.setOrientation(QtCore.Qt.Horizontal)
        self.pairSlider.setObjectName("pairSlider")
        self.verticalLayout_3.addWidget(self.pairSlider)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.excludeButton = QtWidgets.QToolButton(self.groupBox_2)
        self.excludeButton.setObjectName("excludeButton")
        self.horizontalLayout_2.addWidget(self.excludeButton)
        self.flipButton = QtWidgets.QToolButton(self.groupBox_2)
        self.flipButton.setObjectName("flipButton")
        self.horizontalLayout_2.addWidget(self.flipButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.maskCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.maskCheckBox.setObjectName("maskCheckBox")
        self.horizontalLayout.addWidget(self.maskCheckBox)
        self.midlineCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.midlineCheckBox.setObjectName("midlineCheckBox")
        self.horizontalLayout.addWidget(self.midlineCheckBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.paintButton = QtWidgets.QToolButton(self.groupBox)
        self.paintButton.setObjectName("paintButton")
        self.gridLayout.addWidget(self.paintButton, 0, 2, 1, 1)
        self.brushSizeSlider = QtWidgets.QSlider(self.groupBox)
        self.brushSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brushSizeSlider.setObjectName("brushSizeSlider")
        self.gridLayout.addWidget(self.brushSizeSlider, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_2.addItem(spacerItem)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(XArrayDisplayWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)

        self.retranslateUi(XArrayDisplayWidget)
        QtCore.QMetaObject.connectSlotsByName(XArrayDisplayWidget)

    def retranslateUi(self, XArrayDisplayWidget):
        _translate = QtCore.QCoreApplication.translate
        XArrayDisplayWidget.setWindowTitle(_translate("XArrayDisplayWidget", "Form"))
        self.groupBox_2.setTitle(_translate("XArrayDisplayWidget", "Controls"))
        self.label.setText(_translate("XArrayDisplayWidget", "Wavelength"))
        self.label_2.setText(_translate("XArrayDisplayWidget", "Pair"))
        self.excludeButton.setText(_translate("XArrayDisplayWidget", "exclude"))
        self.flipButton.setText(_translate("XArrayDisplayWidget", "flip L/R"))
        self.maskCheckBox.setText(_translate("XArrayDisplayWidget", "Show / Edit Mask"))
        self.midlineCheckBox.setText(_translate("XArrayDisplayWidget", "Show Midline"))
        self.groupBox.setTitle(_translate("XArrayDisplayWidget", "Mask Tools"))
        self.paintButton.setText(_translate("XArrayDisplayWidget", "paint"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab), _translate("XArrayDisplayWidget", "Tab 1")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_2),
            _translate("XArrayDisplayWidget", "Tab 2"),
        )
