origTitle = getTitle;
run("Duplicate...", "duplicate");
dupID = getImageID;
AUTOFLORESCENCE_THRESH = 1000;
PHARYNX_THRESH = 1000;
run("Find Edges", "stack");
setThreshold(1000,100000);
run("Analyze Particles...", "size=100-Infinity show=Masks exclude stack");
run("Open", "stack");
selectImage(dupID);
close();