classdef Constants
    %CONSTANTS Summary of this class goes here
    %   Detailed explanation goes here
    
    properties (Constant)
        regions = struct(...
            'prePM7', [1 6], 'pm7', [7 13], ...
            'pm6', [15 21], 'pm5', [25 47], ...
            'pm4', [53 64], 'pm3', [68 93], ...
            'postPM3', [95 100], ...
            'medialAxis', [3 97], ...
            'wholePharynx', [1 100]);
        
        lambda = 0.0891;
    end
end