function  lnorm = ssquare(data, newLength, interpMethod) 
%   SQUARE formats Plot Values to cropped and square intensity matrix
%   This function takes as argument the Plot Value.txt matrix generated by
%   the multiplot function in ImageJ,where Xi= vector of pixel coordinates 
%   and Yi= vector of intensities.
%   This function process each pair of vectors XiYi at a time. First crops
%   the zero elements plus the 2 first and last elements. Second scale and
%   interpolates both vectors to a length normalized vector  (100 rows).
%   The new pair of normalized vectors (lnx and lny) are then stored in a
%   new squared matrix (save as output while denugging)

m=data; % duplicate original matrix 
ncols=size(m,2);
New= zeros(newLength,ncols); % New length normalized matrix to store lnx and lny pairs

%i=ncols/2;

for i=1:ncols
    first = find(data(:,i) > 0, 1, 'first');
    last = find(data(:,i) > 0, 1, 'last');
    
    crop = data(first:last, i);
    orig_x = 1:length(crop);
    new_x = linspace(1, length(crop), newLength);

    resizedvec = interp1(orig_x, crop, new_x, interpMethod);
    New(:,i) = resizedvec.';
end
lnorm = New;